#!/bin/bash
# Wrapper para executar o pseudo-SO

# Verifica se a pasta out existe e se a classe foi compilada
if [ ! -d "out" ]; then
  echo "Erro: O projeto ainda não foi compilado. Rode 'make' primeiro."
  exit 1
fi

# Repassa todos os argumentos passados via terminal ("$@") diretamente para a classe Java
java -cp out Dispatcher "$@"
